### ISSUE TITLE
[Error: Error while sending GNTP request to "localhost:23053"]

### ISSUE THREAD

**Issue by ArvoGuo** [theabraham/growly#8]
node example/simple.js 
[Error: Error while sending GNTP request to "localhost:23053"]

what's wrong ,and what should I do next?

but the module [node-notifier]  depanded on growly, I can run well.

**Comment by ArvoGuo** [comment]
and more, 

```
node example/bakery.js 

fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'muffin.png'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at GNTP.add (/Users/Arvo/github/growly/lib/gntp.js:108:39)
    at Growly.register (/Users/Arvo/github/growly/lib/growly.js:100:10)
    at Object.<anonymous> (/Users/Arvo/github/growly/example/bakery.js:10:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
➜  growly git:(master) ✗ tree
.
├── HISTORY.md
├── README.md
├── example
│   ├── bakery.js
│   ├── cake.png
│   ├── muffin.png
│   └── simple.js
├── lib
│   ├── gntp.js
│   └── growly.js
└── package.json

2 directories, 9 files
```

**Comment by ArvoGuo** [comment]
I may wrong something. just can't connect 23053.
